### ISSUE TITLE
Linux compile

### ISSUE THREAD

**Issue by master-key-g** [mid-kid/CakesForeveryWan#30]
Hi mid-kid i compile your cakes firmware on linux with make i dont get any error but if i whant now but it on my sd card decrypt 9 wip and uncart dont run any more.
If your whant i can upload my cakes.dat or what ever your need to found this my cakes.dat is bigger then the one in the release folder #

**Comment by mid-kid** [comment]
First of all, I run linux, and do all development on linux. It works, so it deserves the label: Werks on my machine.
Next, cakes has nothing to do with Decrypt9 or Uncart. I have no idea how you're trying to run them and I'm pretty sure that whatever is wrong is not due to cakes.
Finally, if you want me to be able to figure out what's wrong, please specify useful things, like:
- What devkitARM version you're using
- What entrypoint you're using
- If applicable, emuNAND/sysNAND version
- Actually explain what the fuck you're even trying to do because I have no idea what you expect from me.

**Comment by master-key-g** [comment]
I use the least devkitarm  version i found.
I followed this guide https://github.com/Plailect/Guide/wiki/Part-5-%28arm9loaderhax-&-Cakes%29
synand is 10.7.0-32,if i press L on boot i see cakes information cakes 138 patched sys version from cakes tells me 10.4.
My entrypoint is BootCtr9 to load everthing.I whant us my compiled uncart and cakes.dat.
I run it from BootCtr9 ini to start uncart and Decrypt9 way your providet dat files works for me.
I whant from your way are explain way the dat file gets bigger if i us make launcher and smaller if i us make all

**Comment by mid-kid** [comment]
> I run it from BootCtr9 ini to start uncart and Decrypt9 way your providet dat files works for me.

So, Decrypt9 works? What's the problem then?

> I whant from your way are explain way the dat file gets bigger if i us make launcher and smaller if i us make all

Different compilers output different results whenever they feel like it. Stop comparing sizes, as it won't get you anywhere.

**Comment by master-key-g** [comment]
Works only if i us your dat file and not my dat file that i compile yes every compiler gets diff size i know that.Way your dat file works and my dat file not.All Is fine now i found what i make wrong

**Comment by mid-kid** [comment]
Oh. Okay. Could you explain what was wrong for future reference?

**Comment by master-key-g** [comment]
Yes i donwload it new from the git and then i make launcher then make patches and then all then i put all files i got after all on my sd card and now it works dont know way it now works.Only thing that is not working is my uncart version but that comes not from your or my cakes.dat this comes from the uncart git i us.
