### ISSUE TITLE
Boot Splash images?

### ISSUE THREAD

**Issue by WolfWare-Dev** [mid-kid/CakesForeveryWan#51]
This is one feature in other CFW's (Luma3DS for example) I'd love to see in Cakes!

A couple of people suggested I jump on here and give @mid-kid a mention.

**Comment by ghost** [comment]
You could either use a boot manager with splash support or try out BootAnim9 with Cakes as an external payload.

I don't know if @mid-kid would be happy adding this feature, given that he wants to keep his project as simple as possible, with bells & whistles being optional patches rather than integrated in Cakes itself.

**Comment by WolfWare-Dev** [comment]
Okay, I'll give that a look. Thanks a bunch!

**Comment by ghost** [comment]
If you are satisfied with any of those solutions, please feel free to close this issue

**Comment by mid-kid** [comment]
This should happen in a boot manager, indeed.
