### ISSUE TITLE
People are still using this, and all yer links are ded m8

### ISSUE THREAD

**Issue by Multimegamander** [mid-kid/CakesForeveryWan#70]

**Comment by mid-kid** [comment]
Updated the link in the latest release. Are there any more broken links that need updating?

**Comment by Multimegamander** [comment]
every link in the README is ded

**Comment by mid-kid** [comment]
The readme has no links. If you mean the gbatemp thread, I'll fix that later.

**Comment by Multimegamander** [comment]
:p, my bad, I meant the Wiki, kek

**Comment by Multimegamander** [comment]
also, how do I enable debug mode to stream Gen 7 pokemon

**Comment by mid-kid** [comment]
Fixed all the links in the wiki.
CakesFW doesn't support streaming itself. You might want to install svcBackdoor.cake and NTR CFW (I'm not sure if luma supports streaming itself. If it does, just use that.).

**Comment by Multimegamander** [comment]
I do have those GBATemp is a life saver :p, but I'm talking about games that turn off WiFi (All pokemon games, OoT, and some others)

**Comment by mid-kid** [comment]
I'm afraid I can't really help you with this, as I don't own a new 3ds and have no means to test it, nor do I really know what causes NTR CFW to not work with these games.
A quick google reveals that some streaming clients such as snickerstream have an option to send an NFC patch to NTR CFW to patch your console in runtime to allow this. You might want to try that. If it doesn't work, then I'm sorry, but I really don't know.
CakesFW could maybe help with this somehow, but I've ceased development quite a bit ago and have no plans of returning anytime soon.

Closing because the issue has been resolved. Make a new issue if there's any bugs in CakesFW (not missing features) that actively prevent you from doing this.
