### ISSUE TITLE
Did you break something?

### ISSUE THREAD

**Issue by ghost** [mid-kid/CakesForeveryWan#9]
My path has armips in it but it errors out on me:

36724 bytes (37 kB) copied, 0.015 seconds, 2.4 MB/s
python patches/bundle.py patches/emunand/info.json patches/emunand/patches.s bui
ld/patches/emunand out/cakes/patches
'armips' is not recognized as an internal or external command,
operable program or batch file.
Couldn't compile version 0x49 for some reason.
make: **\* [build/patches/emunand.baked] Error 1

**Comment by Syphurith** [comment]
@lavanoid Eh.. Let me have a check. Please try `armips` directly in a newly opened cmd.exe.

```
D:\STATION\CakesFW\CakesFW>set PATH=%PATH%;D:\STATION\devkitPro\devkitARM\bin

D:\STATION\CakesFW\CakesFW>armips
ARMIPS Assembler v0.7d (Jun 12 2015 15:08:40) by Kingcom
Usage: armips.exe file.asm [-temp temp.txt] [-sym symfile.sym]
```

It should produce similar text as above. Cause the python script used `system` function, it should be affected by PATH variable. Built successfully. Your armips may not be in the PATH, sorry.

**Comment by ghost** [comment]
Opened a new cmd and this is the version:

ARMIPS Assembler v0.7d (Apr 1 2013 10:09:41) by Kingcom

**Comment by mid-kid** [comment]
This is a problem with your build environment, unfortunately. Try setting your %PATH% correctly, try getting your python version to respect said %PATH%, or if you can't get it to work, change the armips command executed in the python script (patches/bundle.py) to something like `C:\Wherever\you\put\armips.exe`.
I have changed nothing that could affect this since the last time you reported problems with armips.

**Comment by ghost** [comment]
Hm. Weird. Maybe something has changed in my path, somehow? I'll make the appropriate changes to my build script and see how it goes :)
